server:
    port: 8089
spring:
    application:
        name: movie-theater
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl.defaultZone: http://eurekaserver:8761/eureka